# Generated by Django 4.0 on 2021-12-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappmessage',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='inappmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='participant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_device_notifications', to='auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
